volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: foodgram-db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    depends_on:
      - db
    container_name: foodgram-back
    image: arteic/foodgram_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    container_name: foodgram-front
    image: arteic/foodgram_frontend:latest 
    volumes:
      - static:/result_build

  nginx:
    depends_on:
      - db
      - backend
    container_name: foodgram-proxy
    image: arteic/foodgram_gateway:latest
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - static:/static
      - media:/media
      - ./docs/:/usr/share/nginx/html/api/docs/
