version: '3.3'

volumes:
  static:
  media:

services:

  backend:
    container_name: foodgram-back
    build: backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    container_name: foodgram-front
    build: frontend/
    env_file: .env
    volumes:
      - static:/app/result_build
  nginx:
    container_name: foodgram-proxy
    build: nginx/
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - ../docs/:/usr/share/nginx/html/docs/
      - static:/static
      - media:/media
