volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    container_name: foodgram_db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-back
    image: arteic/foodgram_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    container_name: foodgram-front
    image: arteic/foodgram_frontend:latest 
    command: cp -r /app/result_build/. /static/
    volumes:
      - static:/static

  nginx:
    container_name: foodgram-proxy
    image: arteic/foodgram_gateway:latest 
    ports:
      - "8000:80"
    volumes:
      - static:/static
      - media:/media
